Add README.md
iammouaz/Hello-Micoverse pull request #1
Opened 2021-08-10 17:31 UTC by moazmolki

Add the README.md
Add  a Linter for HTML & CSS

2021-08-10 18:48 UTC, karvel-code requested changes
Hi @moazmolki , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight

- Proper use of gitflow

## Required Changes ♻️
_Check the comments under the review._

- [ ] Please ensure that all your linter checks are green (there should be no existing errors).
- [ ] The pull request should have a descriptive title. This makes your repo look more professional.
- [ ]  Please add the .test file to .gitgnore. Files not directly related to the project should not be committed and added to .gitignore

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- [ ] Removing sections/titles in the README file that do not have a description.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2021-08-10 18:48 UTC, karvel-code commented on README.md
> +
- [ ] OPTIONAL
- [ ] Removing sections/titles in the README file that do not have a description.

2021-08-11 00:01 UTC, barackm requested changes
Hi @iammouaz , 👋 

Great work on making the changes requested by a previous reviewer 👏 👏👏
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet. 😉  😉 

 # STATUS: Required Changes ♻️
### _Check the comments under the review._ 👇 
![](https://media.giphy.com/media/iZKF7CKpEEva2OZE6a/giphy.gif)

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-11 00:01 UTC, barackm commented on README.md
> +To get a local copy up and running follow these simple example steps.
- [ ] [OPTIONAL] Great job on adding a descriptive README, it could also be better to specify the steps you are talking about on how to get the local copy of the project because for now, it is confusing as those steps are not listed.

2021-08-11 00:01 UTC, barackm commented on .gitignore
> +test.md
- [ ] It seems that you have accidentally removed the node_modules folder from the .gitignore file after you have made the requested changes from the previous reviewer, probably while setting up linters. The node_modules is a big folder that we don't need to push to GitHub because it can get regenerated from the package.json file by running the command `npm install`. please let's fix this issue by removing the folder from the repository and adding it to the .gitignore file.

2021-08-11 09:43 UTC, AshakaE approved these changes
### Hi @iammouaz  🙋‍♀️, 

# STATUS APPROVED ✔
Your project is complete!  There is nothing else to say other than... it's time to merge it 🔗 🚢 
Congratulations! 🎉 

Cheers 🥂  and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-11 10:13 UTC, merged